config/routes.rb
CommandSpace::Application.routes.draw do  
  resources :users, only:[:index, :new, :create]
  resources :auths, only:[:new, :create]
  resources :items

  

  delete "auths" => "auths#destroy"
  root 'auths#new'

end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps

  field :author, type: String
  field :item_name, type: String
  field :item_price, type: Integer

  validates :item_name, presence: true
  validates :item_price, presence: true

end

app/models/user.rb
require 'bcrypt' #

class User
  include Mongoid::Document

  attr_accessor :password

  field :username, type: String
  field :salt, type: String
  field :hashed_password, type: String

  validates :username, uniqueness: true

  def authenticate?(password)
  	self.hashed_password == BCrypt::Engine.hash_secret(password, self.salt)
  end

  before_save :hash_word 

  private
  	def hash_word
  		self.salt = BCrypt::Engine.generate_salt
  		self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
  		self.password = nil
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


helper_method :current_user

	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end

	def authenticate_user
		redirect_to auths_url unless current_user
	end

end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	before_action :authenticate_user, only: [:destroy]
 
	def new
		if current_user
			redirect_to root_path
		else
			@user = User.new
		end
	end

	def create
		if params[:user][:username].present?
			user = User.find_by(username: params[:user][:username])
			if user && user.authenticate?(params[:user][:password])
				session[:user_id] = user.id 
				redirect_to items_path
			else
				flash[:error] = "Incorrect Password. Try Again"
				redirect_to new_auth_path
			end
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to new_auth_path
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :verify_logged_in

  def index
    @items = Item.all.sort_by(&:created_at).reverse
    @item = Item.new
    
  end

  def create
    @item = Item.new(params.require(:item).permit(:item_name, :item_price))
    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params.require(:item).permit(:item_name, :item_price))
      redirect_to items_path
    else
      flash[:error] = "List not udpated"
      render 'edit'
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end

  private

  def verify_logged_in
    if !current_user
      flash[:error] = "Login require"
      redirect_to new_auth_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :verify_not_logged_in, only: [:new, :create]

	def new
		@user = User.new
	end

	def create
		@user = User.new(params.require(:user).permit(:username, :password))
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render 'new'
		end
	end

	private
		def verify_not_logged_in
			if current_user
			flash[:error] = "Log out."
			redirect_to root_path
			end
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/auths/new.html.erb
<h1>Command.Space</h1>
<br />
<div class="row">
	<div class="col-md-3"></div>
	
	<div class="col-md-6">
		<%= form_for @user, {url: auths_path, method: 'post'} do |user| %>
			<%= user.text_field :username, :placeholder => "Enter your username", class: "form-control" %><br>
			<%= user.password_field :password, :placeholder => "Enter password", class: "form-control" %><br>
			<%= user.submit "Log in!", class: "btn btn-success" %>
			<%= link_to "Sign up!", new_user_path, class: "btn btn-primary" %>
		<% end %>
	</div>
	
	<div class="col-md-3"></div>
</div>

app/views/items/_form.html.erb
<%= form_for @item, :html => { class: "form-inline", role: "form"} do |f| %>

	<% f.hidden_field :author, value: current_user %>
	
	<!-- Item Name label for screen rears only -->
	<%= f.label :item_name, {class: "sr-only"} %>
	<%= f.text_field :item_name, {placeholder: "Item Name", class: "form-control"}%>
	
	<!-- Item Price label for screen rears only -->
	<%= f.label :item_price, {class: "sr-only"} %> 
	<%= f.text_field :item_price, {placeholder: "Item Price", class: "form-control"} %>

	<%= f.button(type: 'submit', class: "btn btn-default") do %>
			<span class="glyphicon glyphicon-plus"></span>
	<% end %>

<% end %>

app/views/items/_new.html.erb
<%= form_for @newitem, :html => { class: "form-inline", role: "form"} do |f| %>
	<div class="form-group">
		<% f.hidden_field :author, value: current_user %>
		
		<!-- Item Name label for screen rears only -->
		<%= f.label :item_name, {class: "sr-only"} %>
		<%= f.text_field :item_name, {placeholder: "Item Name", class: "form-control"}%>
		
		<!-- Item Price label for screen rears only -->
		<%= f.label :item_price, {class: "sr-only"} %> 
		<%= f.text_field :item_price, {placeholder: "Item Price", class: "form-control"} %>

		<%= f.button(type: 'submit', class: "btn btn-default") do %>
				<span class="glyphicon glyphicon-plus"></span> 
		<% end %>
	</div>

<% end %>

app/views/items/edit.html.erb
<h1>Edit </h1>
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-6">
		<%= form_for @item, :html => { class: "form-inline", role: "form"} do |f| %>

			<% f.hidden_field :author, value: current_user %>
			
			<!-- Item Name label for screen rears only -->
			<%= f.label :item_name, {class: "sr-only"} %>
			<%= f.text_field :item_name, {placeholder: "Item Name", class: "form-control"}%>
			
			<!-- Item Price label for screen rears only -->
			<%= f.label :item_price, {class: "sr-only"} %> 
			<%= f.text_field :item_price, {placeholder: "Item Price", class: "form-control"} %>

			<%= f.button(type: 'submit', class: "btn btn-default") do %>
					<span class="glyphicon glyphicon-floppy-disk"></span>
			<% end %>

		<% end %>
	</div>
	<div class="col-md-2"></div>
</div>

app/views/items/index.html.erb
<%= button_to "Log Out", auths_path, method: :delete, class: "btn btn-danger" %>

<h1><%= current_user.username %>'s list of crap</h1>

<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-3"></div>
	
	<div class="col-md-6">
		<br />

		<table class="table table-hover">
			<tr>
				<th>Image</th>
				<th>Name</th>	
				<th>Price</th>
				<th></th>	
				<th></th>	
			</tr>
			<% @items.each do |i| %>
				<tr>
					<td>Image Placeholder</td>
					<td><%= i.item_name %></td>
					<td><%= number_to_currency(i.item_price) %></td>
					<td>						
						<%= button_to edit_item_path(i.id), {action: "edit", method: :get, class: "btn btn-default"} do %>
							<span class="glyphicon glyphicon-pencil"></span>
						<% end %>
					</td>
					<td>
						<%= button_to item_path(i.id), {action: "destroy", method: :delete, class: "btn btn-default", confirm: "Are you sure?"} do %>
							<span class="glyphicon glyphicon-minus"></span>
						<% end %>
					</td>
				</tr>
			<% end %>
		</table>

	</div>

	<div class="col-md-3"></div>
</div>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/_form.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<%= form_for @user do |f|%>
			<div class="col-xs-12">
				<%=f.text_field :username, :placeholder => "Username", class: "form-control" %>
			</div>
			
			<br />
			<br />
			
			<div class="col-xs-12">
				<%=f.password_field :password, :placeholder => "Password", class: "form-control" %><br />
			</div>

			<%= f.submit "Sign up", class: "btn btn-success" %>
			<%= link_to "Log in", new_auth_path, class: "btn btn-primary" %>

		<% end %>
	</div>
	<div class="col-md-3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Command Space</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	
	<body>
		<p class="script"><%= flash[:error] %></p>
		<div class="container">

		<%= yield %>
			
		</div>

	</body>
</html>

app/views/users/new.html.erb
<h1>Command.Space</h1>
<br />
<div class="center-div">
	<%= render 'layouts/form' %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>